export const data = [
    {
        edges: {
            back: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.5537062651751433,
                            x2: 0.8880112354277152,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "minor",
                },
                left: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.9478067440521872,
                            y2: 0.04220428818112065,
                            kind: "whitening",
                            side: "back",
                            deduction: "minor",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "minor",
                },
                right: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.033006763238679966,
                            y2: 0.08749640253261705,
                            kind: "whitening",
                            side: "back",
                            deduction: "minimal",
                        },
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.21719709324635456,
                            y2: 0.4412953280890253,
                            kind: "misshaped",
                            side: "back",
                            deduction: "minimal",
                        },
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.4996222659247889,
                            y2: 0.9324695414428245,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "minor",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.9209456542594013,
                            x2: 0.16806768035303166,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.1266248561013047,
                            x2: 0.056786022640061384,
                            y1: 1,
                            y2: 1,
                            kind: "misshaped",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "minor",
                },
            },
            front: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.5537062651751433,
                            x2: 0.8880112354277152,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                left: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.9355273887183423,
                            y2: 0.06676299884881032,
                            kind: "wear",
                            side: "front",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                right: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.4996222659247889,
                            y2: 0.9324695414428245,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.9209456542594013,
                            x2: 0.16806768035303166,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.1266248561013047,
                            x2: 0.056786022640061384,
                            y1: 1,
                            y2: 1,
                            kind: "misshaped",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
            },
        },
        corners: {
            back: {
                bent: "none",
                soft: "minimal",
                wear: "minimal",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 0,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 90,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "minimal",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 270,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "minimal",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 180,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                },
                damaged: "minimal",
                rounding: "minimal",
                whitening: "minimal",
            },
            front: {
                bent: "none",
                soft: "minimal",
                wear: "minimal",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 0,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 90,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "none",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 270,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 180,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                },
                damaged: "minimal",
                rounding: "minimal",
                whitening: "none",
            },
        },
        surface: {
            back: {
                dent: "none",
                labels: [
                    {
                        h: 0.007449041014221919,
                        w: 0.011924462592596163,
                        x: 0.11364227687018719,
                        y: 0.05840251799907968,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.008286186359824033,
                        w: 0.018289027096333843,
                        x: 0.9270079431415015,
                        y: 0.5684899775731798,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.008662831194361509,
                        w: 0.03239770514207718,
                        x: 0.719558121505943,
                        y: 0.9586940261539861,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.015442438216035748,
                        w: 0.03292024877340094,
                        x: 0.2884596256637876,
                        y: 0.8272449789004134,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.011675989870661208,
                        w: 0.02351446340957211,
                        x: 0.06063060240660001,
                        y: 0.4223517817726461,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.00985244363244725,
                        w: 0.058531056899661864,
                        x: 0.04369752428222482,
                        y: 0.3993207447415565,
                        kind: "scratch",
                        deduction: "minimal",
                    },
                ],
                bending: "none",
                scratch: "minimal",
                creasing: "none",
                spotting: "minor",
                printLine: "none",
            },
            front: {
                dent: "none",
                labels: [
                    {
                        h: 0.009237832611384528,
                        w: 0.017398967393857545,
                        x: 0.13232017515808409,
                        y: 0.05901871361751124,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.022942629723513464,
                        w: 0.043362843659863426,
                        x: 0.5630041840530644,
                        y: 0.8691873869075722,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                ],
                bending: "none",
                scratch: "none",
                creasing: "none",
                spotting: "minimal",
                printLine: "none",
            },
        },
        centering: {
            back: {
                top: 0.06045147352781299,
                left: 0.08467611221682417,
                right: 0.07305548980582666,
                bottom: 0.0499160816653218,
            },
            front: {
                top: 0.05759252115511721,
                left: 0.08387638070276039,
                right: 0.06653090482430957,
                bottom: 0.05246313933225022,
            },
        },
    },
    {
        edges: {
            back: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.7147299175613497,
                            x2: 0.7546072181748467,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "none",
                },
                left: {
                    wear: "minimal",
                    labels: [],
                    misshaped: "none",
                    whitening: "none",
                },
                right: {
                    wear: "minimal",
                    labels: [],
                    misshaped: "none",
                    whitening: "none",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.895699530291411,
                            x2: 0.12806149348159512,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "none",
                },
            },
            front: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.7147299175613497,
                            x2: 0.7546072181748467,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "none",
                },
                left: {
                    wear: "minimal",
                    labels: [],
                    misshaped: "none",
                    whitening: "none",
                },
                right: {
                    wear: "minimal",
                    labels: [],
                    misshaped: "none",
                    whitening: "none",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.895699530291411,
                            x2: 0.12806149348159512,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "none",
                },
            },
        },
        corners: {
            back: {
                bent: "none",
                soft: "minor",
                wear: "none",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "none",
                        angle: 0,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "none",
                        angle: 90,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "none",
                        angle: 270,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "none",
                        angle: 180,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                },
                damaged: "none",
                rounding: "none",
                whitening: "none",
            },
            front: {
                bent: "none",
                soft: "minor",
                wear: "none",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "none",
                        angle: 0,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "none",
                        angle: 90,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "none",
                        angle: 270,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "none",
                        angle: 180,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                },
                damaged: "none",
                rounding: "none",
                whitening: "none",
            },
        },
        surface: {
            back: {
                dent: "none",
                labels: [],
                bending: "none",
                scratch: "none",
                creasing: "none",
                spotting: "none",
                printLine: "none",
            },
            front: {
                dent: "none",
                labels: [
                    {
                        h: 0.2820512820512818,
                        w: 0.8058702648760755,
                        x: 0.08682075402540222,
                        y: 0.6312576312576312,
                        kind: "spotting",
                        deduction: "minor",
                    },
                    {
                        h: 0.06959706959706963,
                        w: 0.15707640756059094,
                        x: 0.7390293158530731,
                        y: 0.0927960927960928,
                        kind: "spotting",
                        deduction: "minor",
                    },
                ],
                bending: "none",
                scratch: "none",
                creasing: "none",
                spotting: "major",
                printLine: "none",
            },
        },
        centering: {
            back: {
                top: 0.049503181935445346,
                left: 0.052278032189424894,
                right: 0.06394299861915642,
                bottom: 0.05574837282994338,
            },
            front: {
                top: 0.050063703943189465,
                left: 0.07146179621970455,
                right: 0.06878087481702766,
                bottom: 0.05160761077501719,
            },
        },
    },
    {
        edges: {
            back: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.04298373944742901,
                            x2: 0.9508885744435918,
                            y1: 0,
                            y2: 0,
                            kind: "misshaped",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.1765217287029931,
                            x2: 0.4221088353798925,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                left: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.4156779828387135,
                            y2: 0.05331487773739729,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.9524979735057384,
                            y2: 0.45630864347300193,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                right: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.03727314635093168,
                            y2: 0.9689501649844721,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.6722887087490407,
                            x2: 0.6247062068303915,
                            y1: 1,
                            y2: 1,
                            kind: "misshaped",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.5932403587874137,
                            x2: 0.040669368764389646,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.9432019858019954,
                            x2: 0.7144989927091329,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
            },
            front: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.04298373944742901,
                            x2: 0.9508885744435918,
                            y1: 0,
                            y2: 0,
                            kind: "misshaped",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.1765217287029931,
                            x2: 0.4221088353798925,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                left: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.4156779828387135,
                            y2: 0.05331487773739729,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.9524979735057384,
                            y2: 0.45630864347300193,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                right: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.03727314635093168,
                            y2: 0.9689501649844721,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.6722887087490407,
                            x2: 0.6247062068303915,
                            y1: 1,
                            y2: 1,
                            kind: "misshaped",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.5932403587874137,
                            x2: 0.040669368764389646,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.9432019858019954,
                            x2: 0.7144989927091329,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
            },
        },
        corners: {
            back: {
                bent: "minimal",
                soft: "minimal",
                wear: "minimal",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 0,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "minimal",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 90,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 270,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "none",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 180,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "none",
                    },
                },
                damaged: "minimal",
                rounding: "minimal",
                whitening: "none",
            },
            front: {
                bent: "minimal",
                soft: "minimal",
                wear: "minimal",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 0,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "minimal",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 90,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 270,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "minimal",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 180,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "none",
                    },
                },
                damaged: "minimal",
                rounding: "minimal",
                whitening: "minimal",
            },
        },
        surface: {
            back: {
                dent: "none",
                labels: [
                    {
                        h: 0.019684074027777845,
                        w: 0.035973355583875266,
                        x: 0.8358560897656974,
                        y: 0.0908314644431343,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.019001986544408656,
                        w: 0.05247141007178302,
                        x: 0.371610147832181,
                        y: 0.5606759570880449,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.013296383417475924,
                        w: 0.023473160750965574,
                        x: 0.09296801203451054,
                        y: 0.0784071502210651,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                ],
                bending: "none",
                scratch: "none",
                creasing: "none",
                spotting: "minimal",
                printLine: "none",
            },
            front: {
                dent: "none",
                labels: [
                    {
                        h: 0.010831015297718127,
                        w: 0.02170839987898121,
                        x: 0.374675845705054,
                        y: 0.9097026982311929,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.006924747485426375,
                        w: 0.01921318150208684,
                        x: 0.8971745738267396,
                        y: 0.9203561559010796,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                ],
                bending: "none",
                scratch: "none",
                creasing: "none",
                spotting: "minimal",
                printLine: "none",
            },
        },
        centering: {
            back: {
                top: 0.054296110112304924,
                left: 0.10288118052134845,
                right: 0.09786673724815409,
                bottom: 0.05269357621260473,
            },
            front: {
                top: 0.05709418740015678,
                left: 0.07585674351203067,
                right: 0.06425831855537834,
                bottom: 0.05438856105177636,
            },
        },
    },
    {
        edges: {
            back: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.06677499040675365,
                            x2: 0.13047414620107445,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.2793613296239447,
                            x2: 0.9654703089025325,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                left: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.18341687452033772,
                            y2: 0.1404391308518803,
                            kind: "wear",
                            side: "back",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                right: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.06910544448757763,
                            y2: 0.951869419642857,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.5272388238679969,
                            x2: 0.44051587682271687,
                            y1: 1,
                            y2: 1,
                            kind: "misshaped",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.24941840943975446,
                            x2: 0.0521812643898697,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "none",
                },
            },
            front: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.06677499040675365,
                            x2: 0.13047414620107445,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.2793613296239447,
                            x2: 0.9654703089025325,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "minor",
                },
                left: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.5234015253261703,
                            y2: 0.4834936204911743,
                            kind: "wear",
                            side: "front",
                            deduction: "minimal",
                        },
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.3138850249424405,
                            y2: 0.2478834900230238,
                            kind: "whitening",
                            side: "front",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "minor",
                },
                right: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.3835464382763975,
                            y2: 0.4751613451086957,
                            kind: "whitening",
                            side: "front",
                            deduction: "minimal",
                        },
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.06910544448757763,
                            y2: 0.951869419642857,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "minor",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.9554813411358404,
                            x2: 0.8296179489639295,
                            y1: 1,
                            y2: 1,
                            kind: "whitening",
                            side: "front",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.5272388238679969,
                            x2: 0.44051587682271687,
                            y1: 1,
                            y2: 1,
                            kind: "misshaped",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.24941840943975446,
                            x2: 0.0521812643898697,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "minimal",
                    whitening: "minor",
                },
            },
        },
        corners: {
            back: {
                bent: "minimal",
                soft: "minimal",
                wear: "minimal",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 0,
                        damaged: "none",
                        rounding: "minimal",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 90,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "minimal",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 270,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 180,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                },
                damaged: "none",
                rounding: "minimal",
                whitening: "none",
            },
            front: {
                bent: "none",
                soft: "minimal",
                wear: "minimal",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 0,
                        damaged: "none",
                        rounding: "none",
                        whitening: "minimal",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 90,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 270,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 180,
                        damaged: "none",
                        rounding: "none",
                        whitening: "minor",
                    },
                },
                damaged: "none",
                rounding: "none",
                whitening: "minor",
            },
        },
        surface: {
            back: {
                dent: "none",
                labels: [
                    {
                        h: 0.008891131532075075,
                        w: 0.016662724294264027,
                        x: 0.030763649842555356,
                        y: 0.06628756075537205,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                ],
                bending: "none",
                scratch: "none",
                creasing: "none",
                spotting: "minimal",
                printLine: "none",
            },
            front: {
                dent: "none",
                labels: [
                    {
                        h: 0.0030182453059417885,
                        w: 0.01767309118486704,
                        x: 0.44811170429339364,
                        y: 0.059823875194536524,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.013598084869249794,
                        w: 0.024569224171367754,
                        x: 0.885673848446847,
                        y: 0.2585865244662044,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.00915789389153554,
                        w: 0.015599507410392177,
                        x: 0.9075131588213962,
                        y: 0.5138975056847719,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.015588773150882584,
                        w: 0.02977970847014011,
                        x: 0.9286466114525443,
                        y: 0.7491887044109666,
                        kind: "scratch",
                        deduction: "minimal",
                    },
                    {
                        h: 0.013640176507022317,
                        w: 0.017799365982152704,
                        x: 0.8341730535472723,
                        y: 0.7114346444361729,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.014705279497266965,
                        w: 0.02331474011884993,
                        x: 0.19674905497316006,
                        y: 0.5076278476546986,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                ],
                bending: "none",
                scratch: "minimal",
                creasing: "none",
                spotting: "minor",
                printLine: "none",
            },
        },
        centering: {
            back: {
                top: 0.04941687853103628,
                left: 0.06809489056833745,
                right: 0.06384311708704193,
                bottom: 0.051879080442744585,
            },
            front: {
                top: 0.09198511937945748,
                left: 0.06734803690184923,
                right: 0.07177877721046344,
                bottom: 0.07327261479416003,
            },
        },
    },
    {
        edges: {
            back: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.49068929541925466,
                            x2: 0.6801302892080745,
                            y1: 0,
                            y2: 0,
                            kind: "whitening",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.05590668672360249,
                            x2: 0.19643463703416147,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.7243849475931677,
                            x2: 0.9541986121894409,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "minimal",
                },
                left: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.5656118092862625,
                            y2: 0.522634065617805,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.9549628784937888,
                            y2: 0.07297530085403747,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "minimal",
                },
                right: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.05603055448963929,
                            y2: 0.9378417594013821,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "minimal",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.8035243188795088,
                            x2: 0.44512063507290867,
                            y1: 1,
                            y2: 1,
                            kind: "whitening",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.42670160207214125,
                            x2: 0.05525110322333071,
                            y1: 1,
                            y2: 1,
                            kind: "whitening",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.959318639677667,
                            x2: 0.8365250863392173,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "minimal",
                },
            },
            front: {
                top: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.49068929541925466,
                            x2: 0.6801302892080745,
                            y1: 0,
                            y2: 0,
                            kind: "whitening",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.05590668672360249,
                            x2: 0.19643463703416147,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.7243849475931677,
                            x2: 0.9541986121894409,
                            y1: 0,
                            y2: 0,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "minimal",
                },
                left: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.5656118092862625,
                            y2: 0.522634065617805,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0,
                            x2: 0,
                            y1: 0.9549628784937888,
                            y2: 0.07297530085403747,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "minimal",
                },
                right: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 1,
                            x2: 1,
                            y1: 0.05603055448963929,
                            y2: 0.9378417594013821,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "minimal",
                },
                bottom: {
                    wear: "minimal",
                    labels: [
                        {
                            x1: 0.8035243188795088,
                            x2: 0.44512063507290867,
                            y1: 1,
                            y2: 1,
                            kind: "whitening",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.42670160207214125,
                            x2: 0.05525110322333071,
                            y1: 1,
                            y2: 1,
                            kind: "whitening",
                            side: "both",
                            deduction: "minimal",
                        },
                        {
                            x1: 0.959318639677667,
                            x2: 0.8365250863392173,
                            y1: 1,
                            y2: 1,
                            kind: "wear",
                            side: "both",
                            deduction: "minimal",
                        },
                    ],
                    misshaped: "none",
                    whitening: "minimal",
                },
            },
        },
        corners: {
            back: {
                bent: "none",
                soft: "minimal",
                wear: "minimal",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 0,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 90,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "minimal",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 270,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "minimal",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 180,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "none",
                    },
                },
                damaged: "minimal",
                rounding: "minimal",
                whitening: "minimal",
            },
            front: {
                bent: "none",
                soft: "minimal",
                wear: "minimal",
                labels: {
                    topLeft: {
                        x: 0,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 0,
                        damaged: "none",
                        rounding: "none",
                        whitening: "none",
                    },
                    topRight: {
                        x: 1,
                        y: 0,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 90,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "minimal",
                    },
                    bottomLeft: {
                        x: 0,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 270,
                        damaged: "minimal",
                        rounding: "minimal",
                        whitening: "minimal",
                    },
                    bottomRight: {
                        x: 1,
                        y: 1,
                        bent: "none",
                        soft: "minimal",
                        wear: "minimal",
                        angle: 180,
                        damaged: "minimal",
                        rounding: "none",
                        whitening: "minimal",
                    },
                },
                damaged: "minimal",
                rounding: "minimal",
                whitening: "minor",
            },
        },
        surface: {
            back: {
                dent: "none",
                labels: [
                    {
                        h: 0.03240145640246006,
                        w: 0.06861961443421394,
                        x: 0.12975003263033558,
                        y: 0.15050304368560344,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                ],
                bending: "none",
                scratch: "none",
                creasing: "none",
                spotting: "minimal",
                printLine: "none",
            },
            front: {
                dent: "none",
                labels: [
                    {
                        h: 0.02772607208948001,
                        w: 0.038312277435242764,
                        x: 0.2220374326009075,
                        y: 0.12012936321378266,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                    {
                        h: 0.02804846827656699,
                        w: 0.03696007940811653,
                        x: 0.03588483753319866,
                        y: 0.018252168094297992,
                        kind: "spotting",
                        deduction: "minimal",
                    },
                ],
                bending: "none",
                scratch: "none",
                creasing: "none",
                spotting: "minimal",
                printLine: "none",
            },
        },
        centering: {
            back: {
                top: 0.04252713426286798,
                left: 0.054798587242442326,
                right: 0.070646089513687,
                bottom: 0.05406564618116427,
            },
            front: {
                top: 0.048881878748245525,
                left: 0.05830513729968495,
                right: 0.05994281643738353,
                bottom: 0.04493087201203694,
            },
        },
    },
];
